name: CUnit Test Runner

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake sdl2 cunit

    - name: Create Build Directory
      run: mkdir build

    - name: CMake Configure
      working-directory: build
      run: cmake ..

    - name: CMake Build
      working-directory: build
      run: cmake --build .

    - name: Run tests
      working-directory: build/tests
      run: ./z80_tests
